package code_generator;

public enum Statement {
 PRINTLN_STR,
 PRINTLN_INT,
 PRINTLN_BOOL,
 PRINTLN_REFERENCE,
 PRINT_LN,
 PRINT_NULLPOINTER,
 PRINT_STR_MSG,
 PRINTLN_MSG,
 ARRAY_INIT_STRING,
 ARRAY_INIT_INT,
 ARRAY_INIT_PAIR,
 ARRAY_INIT_BOOL,
 ARRAY_INIT_CHAR, 
 ARRAY_INIT_EMPTY;
}
